# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Dev\repo\CEESS\ui\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(321, 129)
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_Password = QtWidgets.QLineEdit(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.gridLayout.addWidget(self.lineEdit_Password, 2, 1, 1, 1)
        self.label_Password = QtWidgets.QLabel(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Password.sizePolicy().hasHeightForWidth())
        self.label_Password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_Password.setFont(font)
        self.label_Password.setObjectName("label_Password")
        self.gridLayout.addWidget(self.label_Password, 2, 0, 1, 1)
        self.label_Account = QtWidgets.QLabel(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Account.sizePolicy().hasHeightForWidth())
        self.label_Account.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_Account.setFont(font)
        self.label_Account.setObjectName("label_Account")
        self.gridLayout.addWidget(self.label_Account, 0, 0, 1, 1)
        self.LineEdit_Account = QtWidgets.QLineEdit(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.LineEdit_Account.setFont(font)
        self.LineEdit_Account.setObjectName("LineEdit_Account")
        self.gridLayout.addWidget(self.LineEdit_Account, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.loginButtom = QtWidgets.QPushButton(Login)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.loginButtom.setFont(font)
        self.loginButtom.setObjectName("loginButtom")
        self.verticalLayout.addWidget(self.loginButtom)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.label_Password.setText(_translate("Login", "密码"))
        self.label_Account.setText(_translate("Login", "账户"))
        self.loginButtom.setText(_translate("Login", "登录"))
