# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dev\Repo\CEESS\ui\Teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeacherMainWindow(object):
    def setupUi(self, TeacherMainWindow):
        TeacherMainWindow.setObjectName("TeacherMainWindow")
        TeacherMainWindow.resize(427, 292)
        self.centralwidget = QtWidgets.QWidget(TeacherMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 100, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        TeacherMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TeacherMainWindow)
        self.statusbar.setObjectName("statusbar")
        TeacherMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TeacherMainWindow)
        QtCore.QMetaObject.connectSlotsByName(TeacherMainWindow)

    def retranslateUi(self, TeacherMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TeacherMainWindow.setWindowTitle(_translate("TeacherMainWindow", "MainWindow"))
        self.label.setText(_translate("TeacherMainWindow", "老师"))
